name: Docker Build and Push

on:
  push:
    branches:
      - master # Change this to your default branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.3 # Use a version of the action that supports Node.js 16

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/graduation_project_client:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/graduation_project_client:latest
